-- 1. USER PROFILES (Stores avatar, UI settings, checklist states, and custom recipes)
CREATE TABLE user_profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  avatar_url TEXT,
  settings JSONB DEFAULT '{}'::jsonb,
  daily_checklist JSONB DEFAULT '{}'::jsonb,
  recipe_store JSONB DEFAULT '{"favorites":[],"saved":[],"recent":[],"reviews":[],"weekly":[],"shopping":[],"reactions":[]}'::jsonb,
  weekly_plan JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own profile" ON user_profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON user_profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON user_profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- 2. PETS
CREATE TABLE pets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  species TEXT NOT NULL,
  breed TEXT,
  age NUMERIC,
  weight NUMERIC,
  food_pref TEXT,
  health TEXT,
  water_goal NUMERIC DEFAULT 500,
  activity_level TEXT DEFAULT 'Moderate',
  breed_traits JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE pets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own pets" ON pets FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own pets" ON pets FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own pets" ON pets FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own pets" ON pets FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 3. FEEDING & ACTIVITY LOGS
CREATE TABLE feeding_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  pet_id BIGINT REFERENCES pets(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'fed', 'water'
  amount NUMERIC,
  note TEXT,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE feeding_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own feeding logs" ON feeding_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own feeding logs" ON feeding_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own feeding logs" ON feeding_logs FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own feeding logs" ON feeding_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 4. STOCK ITEMS (Inventory)
CREATE TABLE stock_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'food', 'medicine'
  quantity NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  threshold NUMERIC NOT NULL,
  decrement_amount NUMERIC NOT NULL
);

ALTER TABLE stock_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own stock items" ON stock_items FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own stock items" ON stock_items FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own stock items" ON stock_items FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own stock items" ON stock_items FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 5. EXPENSES
CREATE TABLE expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  category TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  notes TEXT
);

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own expenses" ON expenses FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own expenses" ON expenses FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own expenses" ON expenses FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own expenses" ON expenses FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 6. COMMUNITY POSTS
CREATE TABLE community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view community posts" ON community_posts FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert own community posts" ON community_posts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own community posts" ON community_posts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own community posts" ON community_posts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 7. CART ITEMS
CREATE TABLE cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_id TEXT NOT NULL,
  quantity INTEGER NOT NULL
);

ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own cart" ON cart_items FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own cart" ON cart_items FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own cart" ON cart_items FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own cart" ON cart_items FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 8. SCAN HISTORY
CREATE TABLE scan_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  result JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE scan_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own scans" ON scan_history FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own scans" ON scan_history FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- 9. CARE TASKS
CREATE TABLE care_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  text TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE NOT NULL,
  date DATE NOT NULL
);

ALTER TABLE care_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own tasks" ON care_tasks FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tasks" ON care_tasks FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tasks" ON care_tasks FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own tasks" ON care_tasks FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 10. ORDERS
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own orders" ON orders FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own orders" ON orders FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- 11. MOOD LOGS
CREATE TABLE mood_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  pet_id BIGINT REFERENCES pets(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  label TEXT NOT NULL
);

ALTER TABLE mood_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own moods" ON mood_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own moods" ON mood_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own moods" ON mood_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 12. MEDICATIONS
CREATE TABLE meds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  dosage TEXT,
  frequency TEXT,
  next_due TIMESTAMP WITH TIME ZONE
);

ALTER TABLE meds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own meds" ON meds FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own meds" ON meds FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own meds" ON meds FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own meds" ON meds FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 13. VETERINARY LOGS
CREATE TABLE vet_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  pet_id BIGINT REFERENCES pets(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  clinic TEXT,
  notes TEXT
);

ALTER TABLE vet_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own vet logs" ON vet_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own vet logs" ON vet_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own vet logs" ON vet_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 14. SLEEP LOGS
CREATE TABLE sleep_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  pet_id BIGINT REFERENCES pets(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  hours NUMERIC NOT NULL,
  quality TEXT
);

ALTER TABLE sleep_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own sleep logs" ON sleep_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own sleep logs" ON sleep_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own sleep logs" ON sleep_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 15. PET GALLERIES
CREATE TABLE pet_gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  pet_id BIGINT REFERENCES pets(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE pet_gallery ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own galleries" ON pet_gallery FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own galleries" ON pet_gallery FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own galleries" ON pet_gallery FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 16. WEIGHT HISTORY
CREATE TABLE weight_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  pet_id BIGINT REFERENCES pets(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  weight NUMERIC NOT NULL
);

ALTER TABLE weight_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own weight history" ON weight_history FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own weight history" ON weight_history FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own weight history" ON weight_history FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 17. RECIPE MANAGEMENT
CREATE TABLE custom_recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  ingredients JSONB NOT NULL,
  steps JSONB NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE custom_recipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own custom recipes" ON custom_recipes FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own custom recipes" ON custom_recipes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own custom recipes" ON custom_recipes FOR DELETE TO authenticated USING (auth.uid() = user_id);
